//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppContentText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppContentText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.Resources.AppContentText", typeof(AppContentText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add computer.
        /// </summary>
        internal static string AddComputerPageTitle {
            get {
                return ResourceManager.GetString("AddComputerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add image.
        /// </summary>
        internal static string AddImageButton {
            get {
                return ResourceManager.GetString("AddImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add video.
        /// </summary>
        internal static string AddVideoButton {
            get {
                return ResourceManager.GetString("AddVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email or password are incorrect. Try again!.
        /// </summary>
        internal static string AuthError {
            get {
                return ResourceManager.GetString("AuthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication failed.
        /// </summary>
        internal static string AuthErrorTitle {
            get {
                return ResourceManager.GetString("AuthErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban user.
        /// </summary>
        internal static string BanButton {
            get {
                return ResourceManager.GetString("BanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change view.
        /// </summary>
        internal static string ChangeViewButton {
            get {
                return ResourceManager.GetString("ChangeViewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear filters.
        /// </summary>
        internal static string ClearFilterButton {
            get {
                return ResourceManager.GetString("ClearFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer details.
        /// </summary>
        internal static string ComputerDetailsTab {
            get {
                return ResourceManager.GetString("ComputerDetailsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        internal static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string FilterPageTitle {
            get {
                return ResourceManager.GetString("FilterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string FilterTab {
            get {
                return ResourceManager.GetString("FilterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HDD size.
        /// </summary>
        internal static string HddSizeLabel {
            get {
                return ResourceManager.GetString("HddSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        internal static string ImageTab {
            get {
                return ResourceManager.GetString("ImageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please fill in the fields with correct data!.
        /// </summary>
        internal static string IncorrectFieldsMessage {
            get {
                return ResourceManager.GetString("IncorrectFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fields filled in incorrectly.
        /// </summary>
        internal static string IncorrectFieldsTitle {
            get {
                return ResourceManager.GetString("IncorrectFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        internal static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while logging out of account. Try Again!.
        /// </summary>
        internal static string LogOutError {
            get {
                return ResourceManager.GetString("LogOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout failed.
        /// </summary>
        internal static string LogOutErrorTitle {
            get {
                return ResourceManager.GetString("LogOutErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Made by ITwisterMax.
        /// </summary>
        internal static string MadeByLabel {
            get {
                return ResourceManager.GetString("MadeByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main data.
        /// </summary>
        internal static string MainDataLabel {
            get {
                return ResourceManager.GetString("MainDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main settings.
        /// </summary>
        internal static string MainSettingsTitle {
            get {
                return ResourceManager.GetString("MainSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max value.
        /// </summary>
        internal static string MaxLabel {
            get {
                return ResourceManager.GetString("MaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min value.
        /// </summary>
        internal static string MinLabel {
            get {
                return ResourceManager.GetString("MinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found.
        /// </summary>
        internal static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords must match!.
        /// </summary>
        internal static string PasswordsError {
            get {
                return ResourceManager.GetString("PasswordsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processor cores number.
        /// </summary>
        internal static string ProcessorCoresLabel {
            get {
                return ResourceManager.GetString("ProcessorCoresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processor generation number.
        /// </summary>
        internal static string ProcessorGenerationLabel {
            get {
                return ResourceManager.GetString("ProcessorGenerationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processor threads number.
        /// </summary>
        internal static string ProcessorThreadsLabel {
            get {
                return ResourceManager.GetString("ProcessorThreadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PSU power.
        /// </summary>
        internal static string PsuPowerLabel {
            get {
                return ResourceManager.GetString("PsuPowerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAM size.
        /// </summary>
        internal static string RamSizeLabel {
            get {
                return ResourceManager.GetString("RamSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login now.
        /// </summary>
        internal static string RedirectToLoginPage {
            get {
                return ResourceManager.GetString("RedirectToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register now.
        /// </summary>
        internal static string RedirectToRegistrationPage {
            get {
                return ResourceManager.GetString("RedirectToRegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email or password are incorrect. Try again!.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration failed!.
        /// </summary>
        internal static string RegistrationErrorTitle {
            get {
                return ResourceManager.GetString("RegistrationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        internal static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select language.
        /// </summary>
        internal static string SelectLanguagePlaceholder {
            get {
                return ResourceManager.GetString("SelectLanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show video.
        /// </summary>
        internal static string ShowVideoButton {
            get {
                return ResourceManager.GetString("ShowVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign up.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSD size.
        /// </summary>
        internal static string SsdSizeLabel {
            get {
                return ResourceManager.GetString("SsdSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update image.
        /// </summary>
        internal static string UpdateImageButton {
            get {
                return ResourceManager.GetString("UpdateImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update video.
        /// </summary>
        internal static string UpdateVideoButton {
            get {
                return ResourceManager.GetString("UpdateVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select user email to ban.
        /// </summary>
        internal static string UserEmailToBanPlaceholder {
            get {
                return ResourceManager.GetString("UserEmailToBanPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video not found!.
        /// </summary>
        internal static string VideoNotFoundMessage {
            get {
                return ResourceManager.GetString("VideoNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video.
        /// </summary>
        internal static string VideoTab {
            get {
                return ResourceManager.GetString("VideoTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View video.
        /// </summary>
        internal static string ViewVideoButton {
            get {
                return ResourceManager.GetString("ViewVideoButton", resourceCulture);
            }
        }
    }
}
